### ISSUE TITLE
Variation in the failed cases in Jakarta version for functional test

### ISSUE THREAD

**Issue by Rakshithakrishna2** [edgexfoundry/edgex-taf#626] opened 2022-04-19 09:02 UTC
Hi all,

I am trying to execute functional tests on x86 arch in docker under Jakarta version. Each time the tests are executed, the failure cases varies. 
The results are varying even after the changes being made as mentioned over [slack](https://github.com/edgexfoundry/edgex-taf/pull/603/commits/5ce7c7ef903ba869d6149466aec5960dff9b3928) 

In my case, the first time I run TAF gives 8 failure cases then 2 and 6 failures (files are attached in txt format, please convert to html)
[fail8cases.txt](https://github.com/edgexfoundry/edgex-taf/files/8511490/fail8cases.txt)
[fail2cases.txt](https://github.com/edgexfoundry/edgex-taf/files/8511495/fail2cases.txt)
[fail6cases.txt](https://github.com/edgexfoundry/edgex-taf/files/8511506/fail6cases.txt)

Please let me know why are these results varying everytime we un the TAF, how can I overcome it?
Thank you.!!

**Comment by cherrycl** [comment] 2022-04-20 09:58
Did you just run command "sh run-test.sh" without modify the file?
Did every test execute on the same environment?

And I am also curious why all reports you attached contain 2 execution logs. May I know how to make it?

**Comment by Rakshithakrishna2** [comment] 2022-04-20 11:48
1. For jakarta version, I have modified files according to the [link](https://github.com/edgexfoundry/edgex-taf/pull/603/commits/5ce7c7ef903ba869d6149466aec5960dff9b3928)
2. Yes, everytime I have executed the test in the same environment(same system)
3. Ya, items in logs are duplicating, procedure I follow are:
      Step 1: Exporting the work directory:
                  export WORK_DIR="/home/rakshitha/xxx"
      Step 2: Running the functional-test,
                  sh run-tests.sh x86_64 false functional-test
  About my system environment:
             Docker version: Docker version 20.10.13, build a224086
             Docker-compose version: docker-compose version 1.29.2, build 5becea4c
             Docker IP: 172.17.0.1
             OS version:NAME="Ubuntu"
                                VERSION="18.04.6 LTS (Bionic Beaver)"
                                ID=ubuntu
                                ID_LIKE=debian

**Comment by cherrycl** [comment] 2022-04-21 07:58
Would you please pull the latest commit for Jakarta without any change and run test again?

**Comment by Rakshithakrishna2** [comment] 2022-04-21 18:24
@cherrycl , when I tried running the functional test without changes, while deployment isn't successful (image attached).

![Screenshot from 2022-04-21 23-40-30](https://user-images.githubusercontent.com/88701371/164527657-94437ba1-ac50-4a98-ad00-8269f6f0b9fa.png)

Steps to run are:
         1. export WORK_DIR="/xxx/edgex-taf"
         2.  sh run-tests.sh x86_64 false 1

**Comment by cherrycl** [comment] 2022-04-25 06:12
@Rakshithakrishna2 Please use command `sh run-tests.sh x86_64 false functional-test` or `sh run-test.sh` to run functional test.
See [the updated document](/home/cherry/edgexfoundry/edgex-taf-ginny/TAF/testArtifacts/reports/edgex/log.html).

**Comment by cherrycl** [comment] 2022-04-25 08:01
In TAF tests, we added a validation response time, it may failed sometimes because of low system resources. As I see in your reports the failed cases in sys-mgmt service are because response is slowly. See the below screenshot.

![image](https://user-images.githubusercontent.com/41656797/165045099-79470805-1833-415f-86b2-c081f95bda9f.png)

**Comment by Rakshithakrishna2** [comment] 2022-04-25 10:12
@cherrycl , Is there any solution to change response and make the failure cases, pass? Kindly let me know

**Comment by cherrycl** [comment] 2022-04-26 06:36
You can change the default value of response Time [here](https://github.com/edgexfoundry/edgex-taf/blob/0db93314fe41c7fa6065b9e0791cd2d12cf609fe/TAF/testCaseModules/keywords/common/commonKeywords.robot#L13), or just remove this validation.

**Comment by cloudxxx8** [comment] 2022-04-26 10:11
@Rakshithakrishna2 we cannot reproduce your issue.  all the tests can be passed from our environment.
please try on different machine to see whether it's the environmental or config issues

**Comment by jumpingliu** [comment] 2022-06-06 05:33
@Rakshithakrishna2 
Regarding this issue, you can change the default value of response time or simply remove the validation to pass the test.
So, do you have any further questions? If not, could I close the issue?

**Comment by cherrycl** [comment] 2023-03-30 02:23
Close this issue due to no activity. If you have further question, please file questions on Github Discussions (https://github.com/orgs/edgexfoundry/discussions). Thank you.

**Closed by cherrycl** 2023-03-30 02:23 UTC
